# Generated by Django 4.1.5 on 2023-02-01 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 2, 1, 7, 5, 25, 629185, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
